local ctx = require("aporia.context")

describe("aporia staging", function()
  after_each(function()
    ctx.clear()
  end)

  it("stages an active visual selection without relying on '< marks", function()
    vim.cmd("new /tmp/aporia_test/demo.lua")
    local buf = vim.api.nvim_get_current_buf()
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "alpha", "beta", "gamma", "delta" })
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("ggVjj", true, false, true), "mx", false)
    assert.equals("V", vim.fn.mode())
    assert.is_truthy(ctx.stage_selection(), "staging an active selection failed")
    assert.equals(1, select(1, ctx.summary()))
    vim.cmd("close!")
  end)

  it("stages nothing and reports failure without a selection", function()
    vim.cmd("new /tmp/aporia_test/empty.lua")
    assert.falsy(ctx.stage_selection())
    assert.equals(0, select(1, ctx.summary()))
    vim.cmd("close!")
  end)
end)
