local c = require("aporia.chat")
local ctx = require("aporia.context")

local function geom(w)
  local cfg = vim.api.nvim_win_get_config(w)
  local row = type(cfg.row) == "table" and cfg.row[false] or cfg.row
  local col = type(cfg.col) == "table" and cfg.col[false] or cfg.col
  return { row = row, col = col, width = cfg.width, height = cfg.height }
end

local function usable()
  local g = c.geometry()
  return g.usable
end

describe("aporia sidebar layout", function()
  before_each(function()
    ctx.clear()
    c.hide()
  end)

  after_each(function()
    ctx.clear()
    c.hide()
  end)

  it("stacks chat and input in the same column with no overlap", function()
    c.open()
    local chat, input = geom(c.winid), geom(c.input_winid)
    assert.equals(chat.col, input.col)
    assert.equals(chat.width, input.width)
    assert.is_true(input.row >= chat.row + chat.height + 2)
  end)

  it("fits the stack inside the usable grid with no staged box", function()
    c.open()
    local input = geom(c.input_winid)
    assert.is_true(input.row + input.height + 2 <= usable())
    assert.is_nil(c.staged_winid)
  end)

  it("shows the staged box only when something is staged", function()
    c.open()
    local buf = vim.api.nvim_create_buf(true, false)
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "a", "b", "c" })
    vim.api.nvim_win_set_buf(0, buf)
    ctx.stage_buffer()
    assert.is_not_nil(c.staged_winid)
    ctx.clear()
    c.render()
    assert.is_nil(c.staged_winid)
  end)

  it("sizes the staged box exactly to its content", function()
    c.open()
    local buf = vim.api.nvim_create_buf(true, false)
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "a", "b" })
    vim.api.nvim_win_set_buf(0, buf)
    ctx.stage_buffer()
    local staged = geom(c.staged_winid)
    local lines = vim.api.nvim_buf_line_count(c.staged_bufnr)
    assert.equals(lines, staged.height)
  end)

  it("pushes the input box below the staged box and keeps everything in the grid", function()
    c.open()
    local buf = vim.api.nvim_create_buf(true, false)
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "a", "b", "c" })
    vim.api.nvim_win_set_buf(0, buf)
    ctx.stage_buffer()
    local chat, staged, input = geom(c.winid), geom(c.staged_winid), geom(c.input_winid)
    assert.equals(staged.col, chat.col)
    assert.equals(input.col, chat.col)
    assert.is_true(staged.row >= chat.row + chat.height + 2)
    assert.is_true(input.row >= staged.row + staged.height + 2)
    assert.is_true(input.row + input.height + 2 <= usable())
  end)

  it("lists short refs in the staged box", function()
    c.open()
    vim.cmd("new /tmp/aporia_test/demo.lua")
    local buf = vim.api.nvim_get_current_buf()
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "a", "b", "c", "d" })
    vim.fn.setpos("'<", { buf, 2, 1, 0 })
    vim.fn.setpos("'>", { buf, 2, 1, 0 })
    ctx.stage_selection()
    local lines = vim.api.nvim_buf_get_lines(c.staged_bufnr, 0, -1, false)
    assert.is_truthy(lines[1]:find("staged"))
    assert.equals("/tmp/aporia_test/demo.lua 2-2", lines[3]:gsub("^%s+", ""))
    vim.cmd("close")
  end)
end)
